name = "libarycard-api"
main = "workers/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "libarycard-db"
database_id = "368ab7bc-fb42-4607-a4cf-761dc7795284"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }